    // Achievement.dbc
    DBCFileList[0].col_name[0] = "id";              DBCFileList[0].col_desc[0] = "Entry";
    DBCFileList[0].col_name[1] = "team";            DBCFileList[0].col_desc[1] = "-1=all, 0=horde, 1=alliance";
    DBCFileList[0].col_name[2] = "mapid";           DBCFileList[0].col_desc[2] = "-1=none - Only set if achievement is related to a zone";
    DBCFileList[0].col_name[4] = "name01";          DBCFileList[0].col_desc[4] = "name - each for one locale";
    DBCFileList[0].col_name[5] = "name02";          DBCFileList[0].col_desc[4] = "";
    DBCFileList[0].col_name[6] = "name03";          DBCFileList[0].col_desc[4] = "";
    DBCFileList[0].col_name[7] = "name04";          DBCFileList[0].col_desc[4] = "";
    DBCFileList[0].col_name[8] = "name05";          DBCFileList[0].col_desc[4] = "";
    DBCFileList[0].col_name[9] = "name06";          DBCFileList[0].col_desc[4] = "";
    DBCFileList[0].col_name[10] = "name07";         DBCFileList[0].col_desc[4] = "";
    DBCFileList[0].col_name[11] = "name08";         DBCFileList[0].col_desc[4] = "";
    DBCFileList[0].col_name[12] = "name09";         DBCFileList[0].col_desc[4] = "";
    DBCFileList[0].col_name[13] = "name10";         DBCFileList[0].col_desc[4] = "";
    DBCFileList[0].col_name[14] = "name11";         DBCFileList[0].col_desc[4] = "";
    DBCFileList[0].col_name[15] = "name12";         DBCFileList[0].col_desc[4] = "";
    DBCFileList[0].col_name[16] = "name13";         DBCFileList[0].col_desc[4] = "";
    DBCFileList[0].col_name[17] = "name14";         DBCFileList[0].col_desc[4] = "";
    DBCFileList[0].col_name[18] = "name15";         DBCFileList[0].col_desc[4] = "";
    DBCFileList[0].col_name[19] = "name16";         DBCFileList[0].col_desc[4] = "";
    DBCFileList[0].col_name[21] = "description01";  DBCFileList[0].col_desc[21] = "description - each for one locale";
    DBCFileList[0].col_name[22] = "description02";  DBCFileList[0].col_desc[22] = "";
    DBCFileList[0].col_name[23] = "description03";  DBCFileList[0].col_desc[23] = "";
    DBCFileList[0].col_name[24] = "description04";  DBCFileList[0].col_desc[24] = "";
    DBCFileList[0].col_name[25] = "description05";  DBCFileList[0].col_desc[25] = "";
    DBCFileList[0].col_name[26] = "description06";  DBCFileList[0].col_desc[26] = "";
    DBCFileList[0].col_name[27] = "description07";  DBCFileList[0].col_desc[27] = "";
    DBCFileList[0].col_name[28] = "description08";  DBCFileList[0].col_desc[28] = "";
    DBCFileList[0].col_name[29] = "description09";  DBCFileList[0].col_desc[29] = "";
    DBCFileList[0].col_name[30] = "description10";  DBCFileList[0].col_desc[30] = "";
    DBCFileList[0].col_name[31] = "description11";  DBCFileList[0].col_desc[31] = "";
    DBCFileList[0].col_name[32] = "description12";  DBCFileList[0].col_desc[32] = "";
    DBCFileList[0].col_name[33] = "description13";  DBCFileList[0].col_desc[33] = "";
    DBCFileList[0].col_name[34] = "description14";  DBCFileList[0].col_desc[34] = "";
    DBCFileList[0].col_name[35] = "description15";  DBCFileList[0].col_desc[35] = "";
    DBCFileList[0].col_name[36] = "description16";  DBCFileList[0].col_desc[36] = "";
    DBCFileList[0].col_name[38] = "categoryid";     DBCFileList[0].col_desc[38] = "id of category";
    DBCFileList[0].col_name[39] = "rewpoints";      DBCFileList[0].col_desc[39] = "rewarded points";
    DBCFileList[0].col_name[40] = "order";          DBCFileList[0].col_desc[40] = "order in category";
    DBCFileList[0].col_name[41] = "flags";          DBCFileList[0].col_desc[41] = "flags";
    DBCFileList[0].col_name[43] = "rewarddesc01";   DBCFileList[0].col_desc[43] = "reward description - each for one locale";
    DBCFileList[0].col_name[44] = "rewarddesc02";   DBCFileList[0].col_desc[44] = "";
    DBCFileList[0].col_name[45] = "rewarddesc03";   DBCFileList[0].col_desc[45] = "";
    DBCFileList[0].col_name[46] = "rewarddesc04";   DBCFileList[0].col_desc[46] = "";
    DBCFileList[0].col_name[47] = "rewarddesc05";   DBCFileList[0].col_desc[47] = "";
    DBCFileList[0].col_name[48] = "rewarddesc06";   DBCFileList[0].col_desc[48] = "";
    DBCFileList[0].col_name[49] = "rewarddesc07";   DBCFileList[0].col_desc[49] = "";
    DBCFileList[0].col_name[50] = "rewarddesc08";   DBCFileList[0].col_desc[50] = "";
    DBCFileList[0].col_name[51] = "rewarddesc09";   DBCFileList[0].col_desc[51] = "";
    DBCFileList[0].col_name[52] = "rewarddesc10";   DBCFileList[0].col_desc[52] = "";
    DBCFileList[0].col_name[53] = "rewarddesc11";   DBCFileList[0].col_desc[53] = "";
    DBCFileList[0].col_name[54] = "rewarddesc12";   DBCFileList[0].col_desc[54] = "";
    DBCFileList[0].col_name[55] = "rewarddesc13";   DBCFileList[0].col_desc[55] = "";
    DBCFileList[0].col_name[56] = "rewarddesc14";   DBCFileList[0].col_desc[56] = "";
    DBCFileList[0].col_name[57] = "rewarddesc15";   DBCFileList[0].col_desc[57] = "";
    DBCFileList[0].col_name[58] = "rewarddesc16";   DBCFileList[0].col_desc[58] = "";
    // Achievement_Category.dbc
    DBCFileList[1].col_name[0] = "id";              DBCFileList[1].col_desc[0] = "Entry";
    DBCFileList[1].col_name[1] = "parentid";        DBCFileList[1].col_desc[1] = "Parent id, -1 if none exists";
    DBCFileList[1].col_name[2] = "name01";          DBCFileList[1].col_desc[2] = "Category name - each for one locale";
    DBCFileList[1].col_name[3] = "name02";          DBCFileList[1].col_desc[3] = "";
    DBCFileList[1].col_name[4] = "name03";          DBCFileList[1].col_desc[4] = "";
    DBCFileList[1].col_name[5] = "name04";          DBCFileList[1].col_desc[5] = "";
    DBCFileList[1].col_name[6] = "name05";          DBCFileList[1].col_desc[6] = "";
    DBCFileList[1].col_name[7] = "name06";          DBCFileList[1].col_desc[7] = "";
    DBCFileList[1].col_name[8] = "name07";          DBCFileList[1].col_desc[8] = "";
    DBCFileList[1].col_name[9] = "name08";          DBCFileList[1].col_desc[9] = "";
    DBCFileList[1].col_name[10] = "name09";         DBCFileList[1].col_desc[10] = "";
    DBCFileList[1].col_name[11] = "name10";         DBCFileList[1].col_desc[11] = "";
    DBCFileList[1].col_name[12] = "name11";         DBCFileList[1].col_desc[12] = "";
    DBCFileList[1].col_name[13] = "name12";         DBCFileList[1].col_desc[13] = "";
    DBCFileList[1].col_name[14] = "name13";         DBCFileList[1].col_desc[14] = "";
    DBCFileList[1].col_name[15] = "name14";         DBCFileList[1].col_desc[15] = "";
    DBCFileList[1].col_name[16] = "name15";         DBCFileList[1].col_desc[16] = "";
    DBCFileList[1].col_name[17] = "name16";         DBCFileList[1].col_desc[17] = "";
    DBCFileList[1].col_name[19] = "order";          DBCFileList[1].col_desc[2] = "Sort order";
    // Achievement_Criteria.dbc
    DBCFileList[2].col_name[0] = "id";              DBCFileList[2].col_desc[0] = "Entry";
    DBCFileList[2].col_name[1] = "achievement";     DBCFileList[2].col_desc[1] = "References the achievement this criteria is needed for";
    DBCFileList[2].col_name[3] = "group";           DBCFileList[2].col_desc[3] = "For example: 129 is for professions on skill 450. Not always accurate";
    DBCFileList[2].col_name[4] = "quantity";        DBCFileList[2].col_desc[4] = "Quantitiy required to meet this criteria (level, number of quests, etc)";
    DBCFileList[2].col_name[5] = "category";        DBCFileList[2].col_desc[5] = "Some kind of category. 3 are BG things";
    DBCFileList[2].col_name[6] = "map";             DBCFileList[2].col_desc[6] = "Only set for battlegrounds";
    DBCFileList[2].col_name[7] = "category2";       DBCFileList[2].col_desc[7] = "Nearly the same as the ones before but different sometimes";
    DBCFileList[2].col_name[8] = "map2";            DBCFileList[2].col_desc[8] = "Only set for battlegrounds";
    DBCFileList[2].col_name[9] = "desc01";          DBCFileList[2].col_desc[9] = "Criteria description - each for one locale";
    DBCFileList[2].col_name[10] = "desc02";         DBCFileList[2].col_desc[10] = "";
    DBCFileList[2].col_name[11] = "desc03";         DBCFileList[2].col_desc[11] = "";
    DBCFileList[2].col_name[12] = "desc04";         DBCFileList[2].col_desc[12] = "";
    DBCFileList[2].col_name[13] = "desc05";         DBCFileList[2].col_desc[13] = "";
    DBCFileList[2].col_name[14] = "desc06";         DBCFileList[2].col_desc[14] = "";
    DBCFileList[2].col_name[15] = "desc07";         DBCFileList[2].col_desc[15] = "";
    DBCFileList[2].col_name[16] = "desc08";         DBCFileList[2].col_desc[16] = "";
    DBCFileList[2].col_name[17] = "desc09";         DBCFileList[2].col_desc[17] = "";
    DBCFileList[2].col_name[18] = "desc10";         DBCFileList[2].col_desc[18] = "";
    DBCFileList[2].col_name[19] = "desc11";         DBCFileList[2].col_desc[19] = "";
    DBCFileList[2].col_name[20] = "desc12";         DBCFileList[2].col_desc[20] = "";
    DBCFileList[2].col_name[21] = "desc13";         DBCFileList[2].col_desc[21] = "";
    DBCFileList[2].col_name[22] = "desc14";         DBCFileList[2].col_desc[22] = "";
    DBCFileList[2].col_name[23] = "desc15";         DBCFileList[2].col_desc[23] = "";
    DBCFileList[2].col_name[24] = "desc16";         DBCFileList[2].col_desc[24] = "";
    DBCFileList[2].col_name[25] = "flags";          DBCFileList[2].col_desc[25] = "Some kind of flags";
    DBCFileList[2].col_name[26] = "cflags";         DBCFileList[2].col_desc[26] = "Completion flags";
    DBCFileList[2].col_name[27] = "gflags";         DBCFileList[2].col_desc[27] = "Group flags";
    DBCFileList[2].col_name[29] = "quest_seconds";  DBCFileList[2].col_desc[29] = "Complete quest in %i seconds";
    // AnimationData.dbc
    DBCFileList[3].col_name[0] = "id";              DBCFileList[3].col_desc[0] = "Entry";
    DBCFileList[3].col_name[1] = "name";            DBCFileList[3].col_desc[1] = "Name";
    DBCFileList[3].col_name[2] = "weapon_state";    DBCFileList[3].col_desc[2] = "32 = pull weapons out during animation. 16 and 4 weapons are put back";
    DBCFileList[3].col_name[3] = "flags";           DBCFileList[3].col_desc[3] = "Some kind of flags";
    DBCFileList[3].col_name[5] = "preceeding";      DBCFileList[3].col_desc[5] = "The animation, preceeding this one";
    DBCFileList[3].col_name[6] = "wotlk_id";        DBCFileList[3].col_desc[6] = "Same as id for normal animations (WotLK)";
    DBCFileList[3].col_name[7] = "group";           DBCFileList[3].col_desc[7] = "0 for normal, 3 for fly (WotLK)";
    // AreaGroup.dbc
    DBCFileList[4].col_name[0] = "id";              DBCFileList[4].col_desc[0] = "Entry";
    DBCFileList[4].col_name[1] = "area1";           DBCFileList[4].col_desc[1] = "Area1";
    DBCFileList[4].col_name[2] = "area2";           DBCFileList[4].col_desc[2] = "Area2";
    DBCFileList[4].col_name[3] = "area3";           DBCFileList[4].col_desc[3] = "Area3";
    DBCFileList[4].col_name[4] = "area4";           DBCFileList[4].col_desc[4] = "Area4";
    DBCFileList[4].col_name[5] = "area5";           DBCFileList[4].col_desc[5] = "Area5";
    DBCFileList[4].col_name[6] = "area6";           DBCFileList[4].col_desc[6] = "Area6";
    DBCFileList[4].col_name[7] = "more";            DBCFileList[4].col_desc[7] = "More areas of this group are here (areagroup id)";
    // AreaPOI.dbc
    DBCFileList[5].col_name[0] = "id";              DBCFileList[5].col_desc[0] = "Entry";
    DBCFileList[5].col_name[12] = "pos_x";          DBCFileList[5].col_desc[12] = "X position";
    DBCFileList[5].col_name[13] = "pos_y";          DBCFileList[5].col_desc[13] = "Y position";
    DBCFileList[5].col_name[14] = "pos_z";          DBCFileList[5].col_desc[14] = "Z position";
    DBCFileList[5].col_name[15] = "map_id";         DBCFileList[5].col_desc[15] = "Map id";
    DBCFileList[5].col_name[17] = "area_id";        DBCFileList[5].col_desc[17] = "Area id, -1 if none";
    DBCFileList[5].col_name[18] = "area_desc01";    DBCFileList[5].col_desc[18] = "Area description - each for one locale";
    DBCFileList[5].col_name[19] = "area_desc02";    DBCFileList[5].col_desc[19] = "";
    DBCFileList[5].col_name[20] = "area_desc03";    DBCFileList[5].col_desc[20] = "";
    DBCFileList[5].col_name[21] = "area_desc04";    DBCFileList[5].col_desc[21] = "";
    DBCFileList[5].col_name[22] = "area_desc05";    DBCFileList[5].col_desc[22] = "";
    DBCFileList[5].col_name[23] = "area_desc06";    DBCFileList[5].col_desc[23] = "";
    DBCFileList[5].col_name[24] = "area_desc07";    DBCFileList[5].col_desc[24] = "";
    DBCFileList[5].col_name[25] = "area_desc08";    DBCFileList[5].col_desc[25] = "";
    DBCFileList[5].col_name[26] = "area_desc09";    DBCFileList[5].col_desc[26] = "";
    DBCFileList[5].col_name[27] = "area_desc10";    DBCFileList[5].col_desc[27] = "";
    DBCFileList[5].col_name[28] = "area_desc11";    DBCFileList[5].col_desc[28] = "";
    DBCFileList[5].col_name[29] = "area_desc12";    DBCFileList[5].col_desc[29] = "";
    DBCFileList[5].col_name[30] = "area_desc13";    DBCFileList[5].col_desc[30] = "";
    DBCFileList[5].col_name[31] = "area_desc14";    DBCFileList[5].col_desc[31] = "";
    DBCFileList[5].col_name[32] = "area_desc15";    DBCFileList[5].col_desc[32] = "";
    DBCFileList[5].col_name[33] = "area_desc16";    DBCFileList[5].col_desc[33] = "";
    DBCFileList[5].col_name[35] = "area_state01";   DBCFileList[5].col_desc[35] = "Area state description - each for one locale";
    DBCFileList[5].col_name[36] = "area_state02";   DBCFileList[5].col_desc[36] = "";
    DBCFileList[5].col_name[37] = "area_state03";   DBCFileList[5].col_desc[37] = "";
    DBCFileList[5].col_name[38] = "area_state04";   DBCFileList[5].col_desc[38] = "";
    DBCFileList[5].col_name[39] = "area_state05";   DBCFileList[5].col_desc[39] = "";
    DBCFileList[5].col_name[40] = "area_state06";   DBCFileList[5].col_desc[40] = "";
    DBCFileList[5].col_name[41] = "area_state07";   DBCFileList[5].col_desc[41] = "";
    DBCFileList[5].col_name[42] = "area_state08";   DBCFileList[5].col_desc[42] = "";
    DBCFileList[5].col_name[43] = "area_state09";   DBCFileList[5].col_desc[43] = "";
    DBCFileList[5].col_name[44] = "area_state10";   DBCFileList[5].col_desc[44] = "";
    DBCFileList[5].col_name[45] = "area_state11";   DBCFileList[5].col_desc[45] = "";
    DBCFileList[5].col_name[46] = "area_state12";   DBCFileList[5].col_desc[46] = "";
    DBCFileList[5].col_name[47] = "area_state13";   DBCFileList[5].col_desc[47] = "";
    DBCFileList[5].col_name[48] = "area_state14";   DBCFileList[5].col_desc[48] = "";
    DBCFileList[5].col_name[49] = "area_state15";   DBCFileList[5].col_desc[49] = "";
    DBCFileList[5].col_name[50] = "area_state16";   DBCFileList[5].col_desc[50] = "";
    // AreaTable.dbc
    DBCFileList[6].col_name[0] = "id";              DBCFileList[6].col_desc[0] = "Entry";
    DBCFileList[6].col_name[1] = "map_id";          DBCFileList[6].col_desc[1] = "Map id";
    DBCFileList[6].col_name[2] = "area_id";         DBCFileList[6].col_desc[2] = "Area id - recursive - if this is a sub-area, it will link to its parent area";
    DBCFileList[6].col_name[3] = "index";           DBCFileList[6].col_desc[3] = "Internal index";
    DBCFileList[6].col_name[4] = "type_flag";       DBCFileList[6].col_desc[4] = "Flagging the type of the area, 312 for cities";
    DBCFileList[6].col_name[7] = "sound_ambience";  DBCFileList[6].col_desc[7] = "Sound ambience id";
    DBCFileList[6].col_name[8] = "zone_music";      DBCFileList[6].col_desc[8] = "Zone music id";
    DBCFileList[6].col_name[9] = "zone_intro";      DBCFileList[6].col_desc[9] = "Zone intro music id";
    DBCFileList[6].col_name[10] = "level";          DBCFileList[6].col_desc[10] = "For this level this area was made for";
    DBCFileList[6].col_name[11] = "name01";         DBCFileList[6].col_desc[11] = "Area name - each for one locale";
    DBCFileList[6].col_name[12] = "name02";         DBCFileList[6].col_desc[12] = "";
    DBCFileList[6].col_name[13] = "name03";         DBCFileList[6].col_desc[13] = "";
    DBCFileList[6].col_name[14] = "name04";         DBCFileList[6].col_desc[14] = "";
    DBCFileList[6].col_name[15] = "name05";         DBCFileList[6].col_desc[15] = "";
    DBCFileList[6].col_name[16] = "name06";         DBCFileList[6].col_desc[16] = "";
    DBCFileList[6].col_name[17] = "name07";         DBCFileList[6].col_desc[17] = "";
    DBCFileList[6].col_name[18] = "name08";         DBCFileList[6].col_desc[18] = "";
    DBCFileList[6].col_name[19] = "name09";         DBCFileList[6].col_desc[19] = "";
    DBCFileList[6].col_name[20] = "name10";         DBCFileList[6].col_desc[20] = "";
    DBCFileList[6].col_name[21] = "name11";         DBCFileList[6].col_desc[21] = "";
    DBCFileList[6].col_name[22] = "name12";         DBCFileList[6].col_desc[22] = "";
    DBCFileList[6].col_name[23] = "name13";         DBCFileList[6].col_desc[23] = "";
    DBCFileList[6].col_name[24] = "name14";         DBCFileList[6].col_desc[24] = "";
    DBCFileList[6].col_name[25] = "name15";         DBCFileList[6].col_desc[25] = "";
    DBCFileList[6].col_name[26] = "name16";         DBCFileList[6].col_desc[26] = "";
    DBCFileList[6].col_name[28] = "team";           DBCFileList[6].col_desc[28] = "Territory owner: 2=alliance, 4=horde, 6=neutral";
    // AreaTrigger.dbc
    DBCFileList[7].col_name[0] = "id";              DBCFileList[7].col_desc[0] = "Entry";
    DBCFileList[7].col_name[1] = "map_id";          DBCFileList[7].col_desc[1] = "Map id";
    DBCFileList[7].col_name[2] = "pos_x";           DBCFileList[7].col_desc[2] = "X position";
    DBCFileList[7].col_name[3] = "pos_y";           DBCFileList[7].col_desc[3] = "Y position";
    DBCFileList[7].col_name[4] = "pos_z";           DBCFileList[7].col_desc[4] = "Z position";
    DBCFileList[7].col_name[5] = "size";            DBCFileList[7].col_desc[5] = "Box of size in yards with center at pos_x, pos_y, pos_z";
    DBCFileList[7].col_name[6] = "box_length_x";    DBCFileList[7].col_desc[6] = "Box length extent x edge";
    DBCFileList[7].col_name[7] = "box_length_y";    DBCFileList[7].col_desc[7] = "Box length extent y edge";
    DBCFileList[7].col_name[8] = "box_length_z";    DBCFileList[7].col_desc[8] = "Box length extent z edge";
    DBCFileList[7].col_name[9] = "box_rotation";    DBCFileList[7].col_desc[9] = "Box yaw extent rotation by about z axis";
    // AttackAnimKits.dbc
    DBCFileList[8].col_name[0] = "id";              DBCFileList[8].col_desc[0] = "Entry";
    // AttackAnimTypes.dbc
    DBCFileList[9].col_name[0] = "id";              DBCFileList[9].col_desc[0] = "Entry";
    // AuctionHouse.dbc
    DBCFileList[10].col_name[0] = "id";             DBCFileList[10].col_desc[0] = "Entry";
    // BankBagSlotPrices.dbc
    DBCFileList[11].col_name[0] = "id";             DBCFileList[11].col_desc[0] = "Entry";
    // BannedAddOns.dbc
    DBCFileList[12].col_name[0] = "id";             DBCFileList[12].col_desc[0] = "Entry";
    // BarberShopStyle.dbc
    DBCFileList[13].col_name[0] = "id";             DBCFileList[13].col_desc[0] = "Entry";
    // BattlemasterList.dbc
    DBCFileList[14].col_name[0] = "id";             DBCFileList[14].col_desc[0] = "Entry";
    // CameraShakes.dbc
    DBCFileList[15].col_name[0] = "id";             DBCFileList[15].col_desc[0] = "Entry";
    // Cfg_Categories.dbc
    DBCFileList[16].col_name[0] = "id";             DBCFileList[16].col_desc[0] = "Entry";
    // Cfg_Configs.dbc
    DBCFileList[17].col_name[0] = "id";             DBCFileList[17].col_desc[0] = "Entry";
    // CharacterFacialHairStyles.dbc
    DBCFileList[18].col_name[0] = "raceid";         DBCFileList[18].col_desc[0] = "Race id";
    DBCFileList[18].col_name[1] = "gender";         DBCFileList[18].col_desc[1] = "0 = male, 1 = female";
    DBCFileList[18].col_name[2] = "specificid";     DBCFileList[18].col_desc[2] = "This id is unique per gender, per race";
    DBCFileList[18].col_name[3] = "facialelement1"; DBCFileList[18].col_desc[3] = "Determines mixing of different facial elements, on night elves this is chin hair";
    DBCFileList[18].col_name[4] = "facialelement2"; DBCFileList[18].col_desc[4] = "... on night elves, this controls eyebrows";
    DBCFileList[18].col_name[5] = "facialelement3"; DBCFileList[18].col_desc[5] = "... on night elves, this controls mustache";
    // CharBaseInfo.dbc
    DBCFileList[19].col_name[0] = "";               DBCFileList[19].col_desc[0] = "";
    // CharHairGeosets.dbc
    DBCFileList[20].col_name[0] = "id";             DBCFileList[20].col_desc[0] = "Entry";
    // CharHairTextures.dbc
    DBCFileList[21].col_name[0] = "id";             DBCFileList[21].col_desc[0] = "Entry";
    // CharSections.dbc
    DBCFileList[22].col_name[0] = "id";             DBCFileList[22].col_desc[0] = "Entry";
    // CharStartOutfit.dbc
    DBCFileList[23].col_name[0] = "id";             DBCFileList[23].col_desc[0] = "Entry";
    DBCFileList[23].col_name[1] = "race";           DBCFileList[23].col_desc[1] = "Race id";
    DBCFileList[23].col_name[2] = "class";          DBCFileList[23].col_desc[2] = "Class id";
    DBCFileList[23].col_name[3] = "gender";         DBCFileList[23].col_desc[3] = "0 = male, 1 = female";
    DBCFileList[23].col_name[5] = "item_id01";      DBCFileList[23].col_desc[5] = "24 Item ids, -1 or 0 if none";
    DBCFileList[23].col_name[6] = "item_id02";      DBCFileList[23].col_desc[6] = "";
    DBCFileList[23].col_name[7] = "item_id03";      DBCFileList[23].col_desc[7] = "";
    DBCFileList[23].col_name[8] = "item_id04";      DBCFileList[23].col_desc[8] = "";
    DBCFileList[23].col_name[9] = "item_id05";      DBCFileList[23].col_desc[9] = "";
    DBCFileList[23].col_name[10] = "item_id06";     DBCFileList[23].col_desc[10] = "";
    DBCFileList[23].col_name[11] = "item_id07";     DBCFileList[23].col_desc[11] = "";
    DBCFileList[23].col_name[12] = "item_id08";     DBCFileList[23].col_desc[12] = "";
    DBCFileList[23].col_name[13] = "item_id09";     DBCFileList[23].col_desc[13] = "";
    DBCFileList[23].col_name[14] = "item_id10";     DBCFileList[23].col_desc[14] = "";
    DBCFileList[23].col_name[15] = "item_id11";     DBCFileList[23].col_desc[15] = "";
    DBCFileList[23].col_name[16] = "item_id12";     DBCFileList[23].col_desc[16] = "";
    DBCFileList[23].col_name[17] = "item_id13";     DBCFileList[23].col_desc[17] = "";
    DBCFileList[23].col_name[18] = "item_id14";     DBCFileList[23].col_desc[18] = "";
    DBCFileList[23].col_name[19] = "item_id15";     DBCFileList[23].col_desc[19] = "";
    DBCFileList[23].col_name[20] = "item_id16";     DBCFileList[23].col_desc[20] = "";
    DBCFileList[23].col_name[21] = "item_id17";     DBCFileList[23].col_desc[21] = "";
    DBCFileList[23].col_name[22] = "item_id18";     DBCFileList[23].col_desc[22] = "";
    DBCFileList[23].col_name[23] = "item_id19";     DBCFileList[23].col_desc[23] = "";
    DBCFileList[23].col_name[24] = "item_id20";     DBCFileList[23].col_desc[24] = "";
    DBCFileList[23].col_name[25] = "item_id21";     DBCFileList[23].col_desc[25] = "";
    DBCFileList[23].col_name[26] = "item_id22";     DBCFileList[23].col_desc[26] = "";
    DBCFileList[23].col_name[27] = "item_id23";     DBCFileList[23].col_desc[27] = "";
    DBCFileList[23].col_name[28] = "item_id24";     DBCFileList[23].col_desc[28] = "";
    DBCFileList[23].col_name[53] = "item01_itype";  DBCFileList[23].col_desc[53] = "Item inventory type for each item_id, -1 if item_id is not set";
    DBCFileList[23].col_name[54] = "item02_itype";  DBCFileList[23].col_desc[54] = "";
    DBCFileList[23].col_name[55] = "item03_itype";  DBCFileList[23].col_desc[55] = "";
    DBCFileList[23].col_name[56] = "item04_itype";  DBCFileList[23].col_desc[56] = "";
    DBCFileList[23].col_name[57] = "item05_itype";  DBCFileList[23].col_desc[57] = "";
    DBCFileList[23].col_name[58] = "item06_itype";  DBCFileList[23].col_desc[58] = "";
    DBCFileList[23].col_name[59] = "item07_itype";  DBCFileList[23].col_desc[59] = "";
    DBCFileList[23].col_name[60] = "item08_itype";  DBCFileList[23].col_desc[60] = "";
    DBCFileList[23].col_name[61] = "item09_itype";  DBCFileList[23].col_desc[61] = "";
    DBCFileList[23].col_name[62] = "item10_itype";  DBCFileList[23].col_desc[62] = "";
    DBCFileList[23].col_name[63] = "item11_itype";  DBCFileList[23].col_desc[63] = "";
    DBCFileList[23].col_name[64] = "item12_itype";  DBCFileList[23].col_desc[64] = "";
    DBCFileList[23].col_name[65] = "item13_itype";  DBCFileList[23].col_desc[65] = "";
    DBCFileList[23].col_name[66] = "item14_itype";  DBCFileList[23].col_desc[66] = "";
    DBCFileList[23].col_name[67] = "item15_itype";  DBCFileList[23].col_desc[67] = "";
    DBCFileList[23].col_name[68] = "item16_itype";  DBCFileList[23].col_desc[68] = "";
    DBCFileList[23].col_name[69] = "item17_itype";  DBCFileList[23].col_desc[69] = "";
    DBCFileList[23].col_name[70] = "item18_itype";  DBCFileList[23].col_desc[70] = "";
    DBCFileList[23].col_name[71] = "item19_itype";  DBCFileList[23].col_desc[71] = "";
    DBCFileList[23].col_name[72] = "item20_itype";  DBCFileList[23].col_desc[72] = "";
    DBCFileList[23].col_name[73] = "item21_itype";  DBCFileList[23].col_desc[73] = "";
    DBCFileList[23].col_name[74] = "item22_itype";  DBCFileList[23].col_desc[74] = "";
    DBCFileList[23].col_name[75] = "item23_itype";  DBCFileList[23].col_desc[75] = "";
    DBCFileList[23].col_name[76] = "item24_itype";  DBCFileList[23].col_desc[76] = "";
    // CharTitles.dbc
    DBCFileList[24].col_name[0] = "id";             DBCFileList[24].col_desc[0] = "Entry";
    // CharVariations.dbc
    DBCFileList[25].col_name[0] = "id";             DBCFileList[25].col_desc[0] = "Entry";
    // ChatChannels.dbc
    DBCFileList[26].col_name[0] = "id";             DBCFileList[26].col_desc[0] = "Entry";
    // ChatProfanity.dbc
    DBCFileList[27].col_name[0] = "id";             DBCFileList[27].col_desc[0] = "Entry";
    // ChrClasses.dbc
    DBCFileList[28].col_name[0] = "id";             DBCFileList[28].col_desc[0] = "Entry";
    // ChrRaces.dbc
    DBCFileList[29].col_name[0] = "id";             DBCFileList[29].col_desc[0] = "Entry";
    // CinematicCamera.dbc
    DBCFileList[30].col_name[0] = "id";             DBCFileList[30].col_desc[0] = "Entry";
    // CinematicSequences.dbc
    DBCFileList[31].col_name[0] = "id";             DBCFileList[31].col_desc[0] = "Entry";
    // CreatureDisplayInfo.dbc
    DBCFileList[32].col_name[0] = "id";             DBCFileList[32].col_desc[0] = "Entry";
    DBCFileList[32].col_name[1] = "modeldata_id1";  DBCFileList[32].col_desc[1] = "Creature model data id 1";
    DBCFileList[32].col_name[2] = "modeldata_id2";  DBCFileList[32].col_desc[2] = "Creature model data id 2";
    DBCFileList[32].col_name[3] = "extrainfo_id";   DBCFileList[32].col_desc[3] = "Creature display info extra id";
    DBCFileList[32].col_name[4] = "scale";          DBCFileList[32].col_desc[4] = "Default scale, if not set by server, 1 is the normal size";
    DBCFileList[32].col_name[5] = "opacity";        DBCFileList[32].col_desc[5] = "0 (transparent) to 255 (opaque)";
    DBCFileList[32].col_name[6] = "skin1";          DBCFileList[32].col_desc[6] = "Skins (1-3) that are used in the model";
    DBCFileList[32].col_name[7] = "skin2";          DBCFileList[32].col_desc[7] = "";
    DBCFileList[32].col_name[8] = "skin3";          DBCFileList[32].col_desc[8] = "";
    DBCFileList[32].col_name[9] = "icon";           DBCFileList[32].col_desc[9] = "Used icon";
    DBCFileList[32].col_name[10] = "size_class";    DBCFileList[32].col_desc[10] = "";
    DBCFileList[32].col_name[11] = "blood_id";      DBCFileList[32].col_desc[11] = "Unit blood id";
    DBCFileList[32].col_name[12] = "sound_id";      DBCFileList[32].col_desc[12] = "NPC sounds id (if you interact with them)";
    DBCFileList[32].col_name[13] = "particle_id";   DBCFileList[32].col_desc[13] = "Particle color id";
    DBCFileList[32].col_name[14] = "geosetdata";    DBCFileList[32].col_desc[14] = "Helmet geoset vis data";
    DBCFileList[32].col_name[15] = "effect_id";     DBCFileList[32].col_desc[15] = "Object effect package id";
    // CreatureDisplayInfoExtra.dbc
    DBCFileList[33].col_name[0] = "id";             DBCFileList[33].col_desc[0] = "Entry";
    DBCFileList[33].col_name[1] = "type_id";        DBCFileList[33].col_desc[1] = "Creature type id";
    DBCFileList[33].col_name[2] = "gender";         DBCFileList[33].col_desc[2] = "0 = male, 1 = female";
    DBCFileList[33].col_name[8] = "helm_id";        DBCFileList[33].col_desc[8] = "Item display info id";
    DBCFileList[33].col_name[9] = "shoulder_id";    DBCFileList[33].col_desc[9] = "Item display info id";
    DBCFileList[33].col_name[10] = "shirt_id";      DBCFileList[33].col_desc[10] = "Item display info id";
    DBCFileList[33].col_name[11] = "cuirass_id";    DBCFileList[33].col_desc[11] = "Item display info id";
    DBCFileList[33].col_name[12] = "belt_id";       DBCFileList[33].col_desc[12] = "Item display info id";
    DBCFileList[33].col_name[13] = "legs_id";       DBCFileList[33].col_desc[13] = "Item display info id";
    DBCFileList[33].col_name[14] = "boots_id";      DBCFileList[33].col_desc[14] = "Item display info id";
    DBCFileList[33].col_name[15] = "rings_id";      DBCFileList[33].col_desc[15] = "Item display info id";
    DBCFileList[33].col_name[16] = "gloves_id";     DBCFileList[33].col_desc[16] = "Item display info id";
    DBCFileList[33].col_name[17] = "wrist_id";      DBCFileList[33].col_desc[17] = "Item display info id";
    DBCFileList[33].col_name[18] = "cape_id";       DBCFileList[33].col_desc[18] = "Item display info id";
    DBCFileList[33].col_name[19] = "tbc";           DBCFileList[33].col_desc[19] = "With TBC added (bool)";
    DBCFileList[33].col_name[20] = "texture";       DBCFileList[33].col_desc[20] = "Texture filename";
    // CreatureFamily.dbc
    DBCFileList[34].col_name[0] = "id";             DBCFileList[34].col_desc[0] = "Entry";
    // CreatureModelData.dbc
    DBCFileList[35].col_name[0] = "id";             DBCFileList[35].col_desc[0] = "Entry";
    //DBCFileList[35].col_name[2] = "file";           DBCFileList[35].col_desc[2] = "Model filename";
    //DBCFileList[35].col_name[5] = "speed";          DBCFileList[35].col_desc[5] = "Animation speed";
    //DBCFileList[35].col_name[8] = "hight";          DBCFileList[35].col_desc[8] = "Hight of the model";
    //DBCFileList[35].col_name[9] = "wide";           DBCFileList[35].col_desc[9] = "Wide of the model";
    //DBCFileList[35].col_name[14] = "group_id";      DBCFileList[35].col_desc[14] = "Group id";
    //DBCFileList[35].col_name[15] = "collision";     DBCFileList[35].col_desc[15] = "Size of collision for this model";
    // CreatureMovementInfo.dbc
    DBCFileList[36].col_name[0] = "id";             DBCFileList[36].col_desc[0] = "Entry";
    // CreatureSoundData.dbc
    DBCFileList[37].col_name[0] = "id";             DBCFileList[37].col_desc[0] = "Entry";
    // CreatureSpellData.dbc
    DBCFileList[38].col_name[0] = "id";             DBCFileList[38].col_desc[0] = "Entry";
    // CreatureType.dbc
    DBCFileList[39].col_name[0] = "id";             DBCFileList[39].col_desc[0] = "Entry";
    // CurrencyCategory.dbc
    DBCFileList[40].col_name[0] = "id";             DBCFileList[40].col_desc[0] = "Entry";
    // CurrencyTypes.dbc
    DBCFileList[41].col_name[0] = "id";             DBCFileList[41].col_desc[0] = "Entry";
    // DanceMoves.dbc
    DBCFileList[42].col_name[0] = "id";             DBCFileList[42].col_desc[0] = "Entry";
    // DeathThudLookups.dbc
    DBCFileList[43].col_name[0] = "id";             DBCFileList[43].col_desc[0] = "Entry";
    // DeclinedWord.dbc
    DBCFileList[44].col_name[0] = "id";             DBCFileList[44].col_desc[0] = "Entry";
    // DeclinedWordCases.dbc
    DBCFileList[45].col_name[0] = "id";             DBCFileList[45].col_desc[0] = "Entry";
    // DestructibleModelData.dbc
    DBCFileList[46].col_name[0] = "id";             DBCFileList[46].col_desc[0] = "Entry";
    // DungeonMap.dbc
    DBCFileList[47].col_name[0] = "id";             DBCFileList[47].col_desc[0] = "Entry";
    // DungeonMapChunk.dbc
    DBCFileList[48].col_name[0] = "id";             DBCFileList[48].col_desc[0] = "Entry";
    // DurabilityCosts.dbc
    DBCFileList[49].col_name[0] = "id";             DBCFileList[49].col_desc[0] = "Entry";
    // DurabilityQuality.dbc
    DBCFileList[50].col_name[0] = "id";             DBCFileList[50].col_desc[0] = "Entry";
    // Emotes.dbc
    DBCFileList[51].col_name[0] = "id";             DBCFileList[51].col_desc[0] = "Entry";
    // EmotesText.dbc
    DBCFileList[52].col_name[0] = "id";             DBCFileList[52].col_desc[0] = "Entry";
    // EmotesTextData.dbc
    DBCFileList[53].col_name[0] = "id";             DBCFileList[53].col_desc[0] = "Entry";
    // EmotesTextSound.dbc
    DBCFileList[54].col_name[0] = "id";             DBCFileList[54].col_desc[0] = "Entry";
    // EnvironmentalDamage.dbc
    DBCFileList[55].col_name[0] = "id";             DBCFileList[55].col_desc[0] = "Entry";
    // Exhaustion.dbc
    DBCFileList[56].col_name[0] = "id";             DBCFileList[56].col_desc[0] = "Entry";
    // Faction.dbc
    DBCFileList[57].col_name[0] = "id";             DBCFileList[57].col_desc[0] = "Entry";
    // FactionGroup.dbc
    DBCFileList[58].col_name[0] = "id";             DBCFileList[58].col_desc[0] = "Entry";
    // FactionTemplate.dbc
    DBCFileList[59].col_name[0] = "id";             DBCFileList[59].col_desc[0] = "Entry";
    // FileData.dbc
    DBCFileList[60].col_name[0] = "id";             DBCFileList[60].col_desc[0] = "Entry";
    // FootprintTextures.dbc
    DBCFileList[61].col_name[0] = "id";             DBCFileList[61].col_desc[0] = "Entry";
    // FootstepTerrainLookup.dbc
    DBCFileList[62].col_name[0] = "id";             DBCFileList[62].col_desc[0] = "Entry";
    // GameObjectArtKit.dbc
    DBCFileList[63].col_name[0] = "id";             DBCFileList[63].col_desc[0] = "Entry";
    // GameObjectDisplayInfo.dbc
    DBCFileList[64].col_name[0] = "id";             DBCFileList[64].col_desc[0] = "Entry";
    // GameTables.dbc
    DBCFileList[65].col_name[0] = "";               DBCFileList[65].col_desc[0] = "";
    // GameTips.dbc
    DBCFileList[66].col_name[0] = "id";             DBCFileList[66].col_desc[0] = "Entry";
    // GemProperties.dbc
    DBCFileList[67].col_name[0] = "id";             DBCFileList[67].col_desc[0] = "Entry";
    // GlyphProperties.dbc
    DBCFileList[68].col_name[0] = "id";             DBCFileList[68].col_desc[0] = "Entry";
    // GlyphSlot.dbc
    DBCFileList[69].col_name[0] = "id";             DBCFileList[69].col_desc[0] = "Entry";
    // GMSurveyAnswers.dbc
    DBCFileList[70].col_name[0] = "id";             DBCFileList[70].col_desc[0] = "Entry";
    // GMSurveyCurrentSurvey.dbc
    DBCFileList[71].col_name[0] = "id";             DBCFileList[71].col_desc[0] = "Entry";
    // GMSurveyQuestions.dbc
    DBCFileList[72].col_name[0] = "id";             DBCFileList[72].col_desc[0] = "Entry";
    // GMSurveySurveys.dbc
    DBCFileList[73].col_name[0] = "id";             DBCFileList[73].col_desc[0] = "Entry";
    // GMTicketCategory.dbc
    DBCFileList[74].col_name[0] = "id";             DBCFileList[74].col_desc[0] = "Entry";
    // GroundEffectDoodad.dbc
    DBCFileList[75].col_name[0] = "id";             DBCFileList[75].col_desc[0] = "Entry";
    // GroungEffectTexture.dbc
    DBCFileList[76].col_name[0] = "id";             DBCFileList[76].col_desc[0] = "Entry";
    // gtBarberShopCostBase.dbc
    DBCFileList[77].col_name[0] = "";               DBCFileList[77].col_desc[0] = "";
    // gtChanceToMeleeCrit.dbc
    DBCFileList[78].col_name[0] = "";               DBCFileList[78].col_desc[0] = "";
    // gtChanceToMeleeCritBase.dbc
    DBCFileList[79].col_name[0] = "";               DBCFileList[79].col_desc[0] = "";
    // gtChanceToSpellCrit.dbc
    DBCFileList[80].col_name[0] = "";               DBCFileList[80].col_desc[0] = "";
    // gtChanceToSpellCritBase.dbc
    DBCFileList[81].col_name[0] = "";               DBCFileList[81].col_desc[0] = "";
    // gtCombatRatings.dbc
    DBCFileList[82].col_name[0] = "";               DBCFileList[82].col_desc[0] = "";
    // gtNPCManaCostScaler.dbc
    DBCFileList[83].col_name[0] = "";               DBCFileList[83].col_desc[0] = "";
    // gtOCTClassCombatRatingScalar.dbc
    DBCFileList[84].col_name[0] = "id";             DBCFileList[84].col_desc[0] = "Entry";
    // gtOCTRegenHP.dbc
    DBCFileList[85].col_name[0] = "";               DBCFileList[85].col_desc[0] = "";
    // gtOCTRegenMP.dbc
    DBCFileList[86].col_name[0] = "";               DBCFileList[86].col_desc[0] = "";
    // gtRegenHPPerSpt.dbc
    DBCFileList[87].col_name[0] = "";               DBCFileList[87].col_desc[0] = "";
    // gtRegenMPPerSpt.dbc
    DBCFileList[88].col_name[0] = "";               DBCFileList[88].col_desc[0] = "";
    // HelmetGeosetVisData.dbc
    DBCFileList[89].col_name[0] = "id";             DBCFileList[89].col_desc[0] = "Entry";
    // HolidayDescriptions.dbc
    DBCFileList[90].col_name[0] = "id";             DBCFileList[90].col_desc[0] = "Entry";
    // HolidayNames.dbc
    DBCFileList[91].col_name[0] = "id";             DBCFileList[91].col_desc[0] = "Entry";
    // Holidays.dbc
    DBCFileList[92].col_name[0] = "id";             DBCFileList[92].col_desc[0] = "Entry";
    // Item.dbc
    DBCFileList[93].col_name[0] = "id";             DBCFileList[93].col_desc[0] = "Entry";
    // ItemBagFamily.dbc
    DBCFileList[94].col_name[0] = "id";             DBCFileList[94].col_desc[0] = "Entry";
    // ItemClass.dbc
    DBCFileList[95].col_name[0] = "id";             DBCFileList[95].col_desc[0] = "Entry";
    // ItemCondExtCosts.dbc
    DBCFileList[96].col_name[0] = "id";             DBCFileList[96].col_desc[0] = "Entry";
    // ItemDisplayInfo.dbc
    DBCFileList[97].col_name[0] = "id";             DBCFileList[97].col_desc[0] = "Entry";
    // ItemExtendedCost.dbc
    DBCFileList[98].col_name[0] = "id";             DBCFileList[98].col_desc[0] = "Entry";
    // ItemGroupSounds.dbc
    DBCFileList[99].col_name[0] = "id";             DBCFileList[99].col_desc[0] = "Entry";
    // ItemLimitCategory.dbc
    DBCFileList[100].col_name[0] = "id";            DBCFileList[100].col_desc[0] = "Entry";
    // ItemPetFood.dbc
    DBCFileList[101].col_name[0] = "id";            DBCFileList[101].col_desc[0] = "Entry";
    // ItemPurchaseGroup.dbc
    DBCFileList[102].col_name[0] = "id";            DBCFileList[102].col_desc[0] = "Entry";
    // ItemRandomProperties.dbc
    DBCFileList[103].col_name[0] = "id";            DBCFileList[103].col_desc[0] = "Entry";
    // ItemRandomSuffix.dbc
    DBCFileList[104].col_name[0] = "id";            DBCFileList[104].col_desc[0] = "Entry";
    // ItemSet.dbc
    DBCFileList[105].col_name[0] = "id";            DBCFileList[105].col_desc[0] = "Entry";
    // ItemSubClass.dbc
    DBCFileList[106].col_name[0] = "";              DBCFileList[106].col_desc[0] = "";
    // ItemSubClassMask.dbc
    DBCFileList[107].col_name[0] = "";              DBCFileList[107].col_desc[0] = "";
    // ItemVisualEffects.dbc
    DBCFileList[108].col_name[0] = "id";            DBCFileList[108].col_desc[0] = "Entry";
    // ItemVisuals.dbc
    DBCFileList[109].col_name[0] = "id";            DBCFileList[109].col_desc[0] = "Entry";
    // Languages.dbc
    DBCFileList[110].col_name[0] = "id";            DBCFileList[110].col_desc[0] = "Entry";
    // LanguageWords.dbc
    DBCFileList[111].col_name[0] = "id";            DBCFileList[111].col_desc[0] = "Entry";
    // LFGDungeons.dbc
    DBCFileList[112].col_name[0] = "id";            DBCFileList[112].col_desc[0] = "Entry";
    // Light.dbc
    DBCFileList[113].col_name[0] = "id";            DBCFileList[113].col_desc[0] = "Entry";
    // LightFloatBand.dbc
    DBCFileList[114].col_name[0] = "id";            DBCFileList[114].col_desc[0] = "Entry";
    // LightIntBand.dbc
    DBCFileList[115].col_name[0] = "id";            DBCFileList[115].col_desc[0] = "Entry";
    // LightParams.dbc
    DBCFileList[116].col_name[0] = "id";            DBCFileList[116].col_desc[0] = "Entry";
    // LightSkybox.dbc
    DBCFileList[117].col_name[0] = "id";            DBCFileList[117].col_desc[0] = "Entry";
    // LiquidMaterial.dbc
    DBCFileList[118].col_name[0] = "id";            DBCFileList[118].col_desc[0] = "Entry";
    // LiquidType.dbc
    DBCFileList[119].col_name[0] = "id";            DBCFileList[119].col_desc[0] = "Entry";
    // LoadingScreens.dbc
    DBCFileList[120].col_name[0] = "id";            DBCFileList[120].col_desc[0] = "Entry";
    // LoadingScreenTaxiSplines.dbc
    DBCFileList[121].col_name[0] = "id";            DBCFileList[121].col_desc[0] = "Entry";
    // Lock.dbc
    DBCFileList[122].col_name[0] = "id";            DBCFileList[122].col_desc[0] = "Entry";
    // LockType.dbc
    DBCFileList[123].col_name[0] = "id";            DBCFileList[123].col_desc[0] = "Entry";
    // MailTemplate.dbc
    DBCFileList[124].col_name[0] = "id";            DBCFileList[124].col_desc[0] = "Entry";
    // Map.dbc
    DBCFileList[125].col_name[0] = "id";            DBCFileList[125].col_desc[0] = "Entry";
    DBCFileList[125].col_name[1] = "filename";      DBCFileList[125].col_desc[1] = "Internal filename";
    DBCFileList[125].col_name[2] = "type";          DBCFileList[125].col_desc[2] = "Type of the map: 0=norm, 1=dungeon, 2=raid, 3=pvp_zone, 4=arena";
    DBCFileList[125].col_name[3] = "bg";            DBCFileList[125].col_desc[3] = "Is battleground (bool)";
    DBCFileList[125].col_name[4] = "name01";        DBCFileList[125].col_desc[4] = "Map name - each for one locale";
    DBCFileList[125].col_name[5] = "name02";        DBCFileList[125].col_desc[5] = "";
    DBCFileList[125].col_name[6] = "name03";        DBCFileList[125].col_desc[6] = "";
    DBCFileList[125].col_name[7] = "name04";        DBCFileList[125].col_desc[7] = "";
    DBCFileList[125].col_name[8] = "name05";        DBCFileList[125].col_desc[8] = "";
    DBCFileList[125].col_name[9] = "name06";        DBCFileList[125].col_desc[9] = "";
    DBCFileList[125].col_name[10] = "name07";       DBCFileList[125].col_desc[10] = "";
    DBCFileList[125].col_name[11] = "name08";       DBCFileList[125].col_desc[11] = "";
    DBCFileList[125].col_name[12] = "name09";       DBCFileList[125].col_desc[12] = "";
    DBCFileList[125].col_name[13] = "name10";       DBCFileList[125].col_desc[13] = "";
    DBCFileList[125].col_name[14] = "name11";       DBCFileList[125].col_desc[14] = "";
    DBCFileList[125].col_name[15] = "name12";       DBCFileList[125].col_desc[15] = "";
    DBCFileList[125].col_name[16] = "name13";       DBCFileList[125].col_desc[16] = "";
    DBCFileList[125].col_name[17] = "name14";       DBCFileList[125].col_desc[17] = "";
    DBCFileList[125].col_name[18] = "name15";       DBCFileList[125].col_desc[18] = "";
    DBCFileList[125].col_name[19] = "name16";       DBCFileList[125].col_desc[19] = "";
    DBCFileList[125].col_name[21] = "area_id";      DBCFileList[125].col_desc[21] = "Area table id";
    DBCFileList[125].col_name[22] = "desc_h01";     DBCFileList[125].col_desc[22] = "Description for horde (ingame) - each for one locale";
    DBCFileList[125].col_name[23] = "desc_h02";     DBCFileList[125].col_desc[23] = "";
    DBCFileList[125].col_name[24] = "desc_h03";     DBCFileList[125].col_desc[24] = "";
    DBCFileList[125].col_name[25] = "desc_h04";     DBCFileList[125].col_desc[25] = "";
    DBCFileList[125].col_name[26] = "desc_h05";     DBCFileList[125].col_desc[26] = "";
    DBCFileList[125].col_name[27] = "desc_h06";     DBCFileList[125].col_desc[27] = "";
    DBCFileList[125].col_name[28] = "desc_h07";     DBCFileList[125].col_desc[28] = "";
    DBCFileList[125].col_name[29] = "desc_h08";     DBCFileList[125].col_desc[29] = "";
    DBCFileList[125].col_name[30] = "desc_h09";     DBCFileList[125].col_desc[30] = "";
    DBCFileList[125].col_name[31] = "desc_h10";     DBCFileList[125].col_desc[31] = "";
    DBCFileList[125].col_name[32] = "desc_h11";     DBCFileList[125].col_desc[32] = "";
    DBCFileList[125].col_name[33] = "desc_h12";     DBCFileList[125].col_desc[33] = "";
    DBCFileList[125].col_name[34] = "desc_h13";     DBCFileList[125].col_desc[34] = "";
    DBCFileList[125].col_name[35] = "desc_h14";     DBCFileList[125].col_desc[35] = "";
    DBCFileList[125].col_name[36] = "desc_h15";     DBCFileList[125].col_desc[36] = "";
    DBCFileList[125].col_name[37] = "desc_h16";     DBCFileList[125].col_desc[37] = "";
    DBCFileList[125].col_name[39] = "desc_a01";     DBCFileList[125].col_desc[39] = "Description for alliance - each for one locale";
    DBCFileList[125].col_name[40] = "desc_a02";     DBCFileList[125].col_desc[40] = "";
    DBCFileList[125].col_name[41] = "desc_a03";     DBCFileList[125].col_desc[41] = "";
    DBCFileList[125].col_name[42] = "desc_a04";     DBCFileList[125].col_desc[42] = "";
    DBCFileList[125].col_name[43] = "desc_a05";     DBCFileList[125].col_desc[43] = "";
    DBCFileList[125].col_name[44] = "desc_a06";     DBCFileList[125].col_desc[44] = "";
    DBCFileList[125].col_name[45] = "desc_a07";     DBCFileList[125].col_desc[45] = "";
    DBCFileList[125].col_name[46] = "desc_a08";     DBCFileList[125].col_desc[46] = "";
    DBCFileList[125].col_name[47] = "desc_a09";     DBCFileList[125].col_desc[47] = "";
    DBCFileList[125].col_name[48] = "desc_a10";     DBCFileList[125].col_desc[48] = "";
    DBCFileList[125].col_name[49] = "desc_a11";     DBCFileList[125].col_desc[49] = "";
    DBCFileList[125].col_name[50] = "desc_a12";     DBCFileList[125].col_desc[50] = "";
    DBCFileList[125].col_name[51] = "desc_a13";     DBCFileList[125].col_desc[51] = "";
    DBCFileList[125].col_name[52] = "desc_a14";     DBCFileList[125].col_desc[52] = "";
    DBCFileList[125].col_name[53] = "desc_a15";     DBCFileList[125].col_desc[53] = "";
    DBCFileList[125].col_name[54] = "desc_a16";     DBCFileList[125].col_desc[54] = "";
    DBCFileList[125].col_name[56] = "loadscr_id";   DBCFileList[125].col_desc[56] = "Loading screens id";
    DBCFileList[125].col_name[57] = "honor_multi";  DBCFileList[125].col_desc[57] = "Honor multiplicator";
    DBCFileList[125].col_name[58] = "parent_map";   DBCFileList[125].col_desc[58] = "Parent Map ID";
    DBCFileList[125].col_name[59] = "x";            DBCFileList[125].col_desc[59] = "X-Coord";
    DBCFileList[125].col_name[60] = "y";            DBCFileList[125].col_desc[60] = "Y-Coord";
    DBCFileList[125].col_name[61] = "time_of_day";  DBCFileList[125].col_desc[61] = "Set to -1 for everything but Orgrimmar and Dalaran arena. For those, the time of day will change to this.";
    DBCFileList[125].col_name[62] = "expansion";    DBCFileList[125].col_desc[62] = "Expansion ID - Vanilla: 0, BC: 1, WotLK: 2";
    DBCFileList[125].col_name[63] = "reset_time";   DBCFileList[125].col_desc[63] = "Reset time";
    DBCFileList[125].col_name[64] = "number_pl";    DBCFileList[125].col_desc[64] = "Number of Players"; 
    // MapDifficulty.dbc
    DBCFileList[126].col_name[0] = "id";            DBCFileList[126].col_desc[0] = "Entry";
    DBCFileList[126].col_name[1] = "map";           DBCFileList[126].col_desc[1] = "Map ID";
    DBCFileList[126].col_name[2] = "type";          DBCFileList[126].col_desc[2] = "0: normal, 1, 2, 3";
    DBCFileList[126].col_name[3] = "lvl_req01";     DBCFileList[126].col_desc[3] = "Level requirement description (ingame) - each for one locale";
    DBCFileList[126].col_name[4] = "lvl_req02";     DBCFileList[126].col_desc[4] = "";
    DBCFileList[126].col_name[5] = "lvl_req03";     DBCFileList[126].col_desc[5] = "";
    DBCFileList[126].col_name[6] = "lvl_req04";     DBCFileList[126].col_desc[6] = "";
    DBCFileList[126].col_name[7] = "lvl_req05";     DBCFileList[126].col_desc[7] = "";
    DBCFileList[126].col_name[8] = "lvl_req06";     DBCFileList[126].col_desc[8] = "";
    DBCFileList[126].col_name[9] = "lvl_req07";     DBCFileList[126].col_desc[9] = "";
    DBCFileList[126].col_name[10] = "lvl_req08";    DBCFileList[126].col_desc[10] = "";
    DBCFileList[126].col_name[11] = "lvl_req09";    DBCFileList[126].col_desc[11] = "";
    DBCFileList[126].col_name[12] = "lvl_req10";    DBCFileList[126].col_desc[12] = "";
    DBCFileList[126].col_name[13] = "lvl_req11";    DBCFileList[126].col_desc[13] = "";
    DBCFileList[126].col_name[14] = "lvl_req12";    DBCFileList[126].col_desc[14] = "";
    DBCFileList[126].col_name[15] = "lvl_req13";    DBCFileList[126].col_desc[15] = "";
    DBCFileList[126].col_name[16] = "lvl_req14";    DBCFileList[126].col_desc[16] = "";
    DBCFileList[126].col_name[17] = "lvl_req15";    DBCFileList[126].col_desc[17] = "";
    DBCFileList[126].col_name[18] = "lvl_req16";    DBCFileList[126].col_desc[18] = "";
    DBCFileList[126].col_name[19] = "";             DBCFileList[126].col_desc[19] = "";
    DBCFileList[126].col_name[20] = "reset_time";   DBCFileList[126].col_desc[20] = "In seconds";
    DBCFileList[126].col_name[21] = "number_pl";    DBCFileList[126].col_desc[21] = "Number of Players";
    DBCFileList[126].col_name[22] = "";           DBCFileList[126].col_desc[22] = "";
    // Material.dbc
    DBCFileList[127].col_name[0] = "id";            DBCFileList[127].col_desc[0] = "Entry";
    // Movie.dbc
    DBCFileList[128].col_name[0] = "id";            DBCFileList[128].col_desc[0] = "Entry";
    // MovieFileData.dbc
    DBCFileList[129].col_name[0] = "id";            DBCFileList[129].col_desc[0] = "Entry";
    // MovieVariation.dbc
    DBCFileList[130].col_name[0] = "id";            DBCFileList[130].col_desc[0] = "Entry";
    // NameGen.dbc
    DBCFileList[131].col_name[0] = "id";            DBCFileList[131].col_desc[0] = "Entry";
    // NamesProfanity.dbc
    DBCFileList[132].col_name[0] = "id";            DBCFileList[132].col_desc[0] = "Entry";
    // NamesReserved.dbc
    DBCFileList[133].col_name[0] = "id";            DBCFileList[133].col_desc[0] = "Entry";
    // NPCSounds.dbc
    DBCFileList[134].col_name[0] = "id";            DBCFileList[134].col_desc[0] = "Entry";
    // ObjectEffect.dbc
    DBCFileList[135].col_name[0] = "id";            DBCFileList[135].col_desc[0] = "Entry";
    // ObjectEffectGroup.dbc
    DBCFileList[136].col_name[0] = "id";            DBCFileList[136].col_desc[0] = "Entry";
    // ObjectEffectModifier.dbc
    DBCFileList[137].col_name[0] = "id";            DBCFileList[137].col_desc[0] = "Entry";
    // ObjectEffectPackage.dbc
    DBCFileList[138].col_name[0] = "id";            DBCFileList[138].col_desc[0] = "Entry";
    // ObjectEffectPackageElem.dbc
    DBCFileList[139].col_name[0] = "id";            DBCFileList[139].col_desc[0] = "Entry";
    // OverrideSpellData.dbc
    DBCFileList[140].col_name[0] = "id";            DBCFileList[140].col_desc[0] = "Entry";
    // Package.dbc
    DBCFileList[141].col_name[0] = "id";            DBCFileList[141].col_desc[0] = "Entry";
    // PageTextMaterial.dbc.dbc
    DBCFileList[142].col_name[0] = "id";            DBCFileList[142].col_desc[0] = "Entry";
    // PaperDollItemFrame.dbc
    DBCFileList[143].col_name[0] = "";              DBCFileList[143].col_desc[0] = "";
    // ParticleColor.dbc
    DBCFileList[144].col_name[0] = "id";            DBCFileList[144].col_desc[0] = "Entry";
    // PetitionType.dbc
    DBCFileList[145].col_name[0] = "id";            DBCFileList[145].col_desc[0] = "Entry";
    // PetPersonality.dbc
    DBCFileList[146].col_name[0] = "id";            DBCFileList[146].col_desc[0] = "Entry";
    // PowerDisplay.dbc
    DBCFileList[147].col_name[0] = "id";            DBCFileList[147].col_desc[0] = "Entry";
    // QuestInfo.dbc
    DBCFileList[148].col_name[0] = "id";            DBCFileList[148].col_desc[0] = "Entry";
    // QuestSort.dbc
    DBCFileList[149].col_name[0] = "id";            DBCFileList[149].col_desc[0] = "Entry";
    // RandPropPoints.dbc
    DBCFileList[150].col_name[0] = "id";            DBCFileList[150].col_desc[0] = "Entry";
    // Resistances.dbc
    DBCFileList[151].col_name[0] = "id";            DBCFileList[151].col_desc[0] = "Entry";
    // ScalingStatDistribution.dbc
    DBCFileList[152].col_name[0] = "id";            DBCFileList[152].col_desc[0] = "Entry";
    // ScalingStatValues.dbc
    DBCFileList[153].col_name[0] = "id";            DBCFileList[153].col_desc[0] = "Entry";
    // ScreenEffect.dbc
    DBCFileList[154].col_name[0] = "id";            DBCFileList[154].col_desc[0] = "Entry";
    // ServerMessages.dbc
    DBCFileList[155].col_name[0] = "id";            DBCFileList[155].col_desc[0] = "Entry";
    // SheatheSoundLookups.dbc
    DBCFileList[156].col_name[0] = "id";            DBCFileList[156].col_desc[0] = "Entry";
    // SkillCostsData.dbc
    DBCFileList[157].col_name[0] = "id";            DBCFileList[157].col_desc[0] = "Entry";
    // SkillLine.dbc
    DBCFileList[158].col_name[0] = "id";            DBCFileList[158].col_desc[0] = "Entry";
    // SkillLineAbility.dbc
    DBCFileList[159].col_name[0] = "id";            DBCFileList[159].col_desc[0] = "Entry";
    // SkillLineCategory.dbc
    DBCFileList[160].col_name[0] = "id";            DBCFileList[160].col_desc[0] = "Entry";
    // SkillRaceClassInfo.dbc
    DBCFileList[161].col_name[0] = "id";            DBCFileList[161].col_desc[0] = "Entry";
    // SkillTiers.dbc
    DBCFileList[162].col_name[0] = "id";            DBCFileList[162].col_desc[0] = "Entry";
    // SoundAmbience.dbc
    DBCFileList[163].col_name[0] = "id";            DBCFileList[163].col_desc[0] = "Entry";
    // SoundEmitters.dbc
    DBCFileList[164].col_name[0] = "id";            DBCFileList[164].col_desc[0] = "Entry";
    // SoundEntries.dbc
    DBCFileList[165].col_name[0] = "id";            DBCFileList[165].col_desc[0] = "Entry";
    // SoundEntriesAdvanced.dbc
    DBCFileList[166].col_name[0] = "id";            DBCFileList[166].col_desc[0] = "Entry";
    // SoundFilter.dbc
    DBCFileList[167].col_name[0] = "id";            DBCFileList[167].col_desc[0] = "Entry";
    // SoundFilterElem.dbc
    DBCFileList[168].col_name[0] = "id";            DBCFileList[168].col_desc[0] = "Entry";
    // SoundProviderPreferences.dbc
    DBCFileList[169].col_name[0] = "id";            DBCFileList[169].col_desc[0] = "Entry";
    // SoundSamplePreferences.dbc
    DBCFileList[170].col_name[0] = "id";            DBCFileList[170].col_desc[0] = "Entry";
    // SoundWaterType.dbc
    DBCFileList[171].col_name[0] = "id";            DBCFileList[171].col_desc[0] = "Entry";
    // SpamMessages.dbc
    DBCFileList[172].col_name[0] = "id";            DBCFileList[172].col_desc[0] = "Entry";
    // Spell.dbc
    DBCFileList[173].col_name[0] = "id";            DBCFileList[173].col_desc[0] = "Entry";
    // SpellCastTimes.dbc
    DBCFileList[174].col_name[0] = "id";            DBCFileList[174].col_desc[0] = "Entry";
    // SpellCategory.dbc
    DBCFileList[175].col_name[0] = "id";            DBCFileList[175].col_desc[0] = "Entry";
    // SpellChainEffects.dbc
    DBCFileList[176].col_name[0] = "id";            DBCFileList[176].col_desc[0] = "Entry";
    // SpellDescriptionVariables.dbc
    DBCFileList[177].col_name[0] = "id";            DBCFileList[177].col_desc[0] = "Entry";
    // SpellDispelType.dbc
    DBCFileList[178].col_name[0] = "id";            DBCFileList[178].col_desc[0] = "Entry";
    // SpellDuration.dbc
    DBCFileList[179].col_name[0] = "id";            DBCFileList[179].col_desc[0] = "Entry";
    // SpellEffectCameraShakes.dbc
    DBCFileList[180].col_name[0] = "id";            DBCFileList[180].col_desc[0] = "Entry";
    // SpellFocusObject.dbc
    DBCFileList[181].col_name[0] = "id";            DBCFileList[181].col_desc[0] = "Entry";
    // SpellIcon.dbc
    DBCFileList[182].col_name[0] = "id";            DBCFileList[182].col_desc[0] = "Entry";
    // SpellItemEnchantment.dbc
    DBCFileList[183].col_name[0] = "id";            DBCFileList[183].col_desc[0] = "Entry";
    // SpellItemEnchantmentCondition.dbc
    DBCFileList[184].col_name[0] = "id";            DBCFileList[184].col_desc[0] = "Entry";
    // SpellMechanic.dbc
    DBCFileList[185].col_name[0] = "id";            DBCFileList[185].col_desc[0] = "Entry";
    // SpellMissile.dbc
    DBCFileList[186].col_name[0] = "id";            DBCFileList[186].col_desc[0] = "Entry";
    // SpellMissileMotion.dbc
    DBCFileList[187].col_name[0] = "id";            DBCFileList[187].col_desc[0] = "Entry";
    // SpellRadius.dbc
    DBCFileList[188].col_name[0] = "id";            DBCFileList[188].col_desc[0] = "Entry";
    // SpellRange.dbc
    DBCFileList[189].col_name[0] = "id";            DBCFileList[189].col_desc[0] = "Entry";
    // SpellRuneCost.dbc
    DBCFileList[190].col_name[0] = "id";            DBCFileList[190].col_desc[0] = "Entry";
    // SpellShapeshiftForm.dbc
    DBCFileList[191].col_name[0] = "id";            DBCFileList[191].col_desc[0] = "Entry";
    // SpellVisual.dbc
    DBCFileList[192].col_name[0] = "id";            DBCFileList[192].col_desc[0] = "Entry";
    // SpellVisualEffectName.dbc
    DBCFileList[193].col_name[0] = "id";            DBCFileList[193].col_desc[0] = "Entry";
    // SpellVisualKit.dbc
    DBCFileList[194].col_name[0] = "id";            DBCFileList[194].col_desc[0] = "Entry";
    // SpellVisualKitAreaModel.dbc
    DBCFileList[195].col_name[0] = "id";            DBCFileList[195].col_desc[0] = "Entry";
    // SpellVisualKitModelAttach.dbc
    DBCFileList[196].col_name[0] = "id";            DBCFileList[196].col_desc[0] = "Entry";
    // SpellVisualPrecastTransitions.dbc
    DBCFileList[197].col_name[0] = "id";            DBCFileList[197].col_desc[0] = "Entry";
    // StableSlotPrices.dbc
    DBCFileList[198].col_name[0] = "id";            DBCFileList[198].col_desc[0] = "Entry";
    // Startup_Strings.dbc
    DBCFileList[199].col_name[0] = "id";            DBCFileList[199].col_desc[0] = "Entry";
    // Stationery.dbc
    DBCFileList[200].col_name[0] = "id";            DBCFileList[200].col_desc[0] = "Entry";
    // StringLookups.dbc
    DBCFileList[201].col_name[0] = "id";            DBCFileList[201].col_desc[0] = "Entry";
    // SummonProperties.dbc
    DBCFileList[202].col_name[0] = "id";            DBCFileList[202].col_desc[0] = "Entry";
    // Talent.dbc
    DBCFileList[203].col_name[0] = "id";            DBCFileList[203].col_desc[0] = "Entry";
    // TalentTab.dbc
    DBCFileList[204].col_name[0] = "id";            DBCFileList[204].col_desc[0] = "Entry";
    // TaxiNodes.dbc
    DBCFileList[205].col_name[0] = "id";            DBCFileList[205].col_desc[0] = "Entry";
    // TaxiPath.dbc
    DBCFileList[206].col_name[0] = "id";            DBCFileList[206].col_desc[0] = "Entry";
    // TaxiPathNode.dbc
    DBCFileList[207].col_name[0] = "id";            DBCFileList[207].col_desc[0] = "Entry";
    // TerrainType.dbc
    DBCFileList[208].col_name[0] = "id";            DBCFileList[208].col_desc[0] = "Entry";
    // TerrainTypeSounds.dbc
    DBCFileList[209].col_name[0] = "id";            DBCFileList[209].col_desc[0] = "Entry";
    // TotemCategory.dbc
    DBCFileList[210].col_name[0] = "id";            DBCFileList[210].col_desc[0] = "Entry";
    // TransportAnimation.dbc
    DBCFileList[211].col_name[0] = "id";            DBCFileList[211].col_desc[0] = "Entry";
    // TransportPhysics.dbc
    DBCFileList[212].col_name[0] = "id";            DBCFileList[212].col_desc[0] = "Entry";
    // TransportRotation.dbc
    DBCFileList[213].col_name[0] = "id";            DBCFileList[213].col_desc[0] = "Entry";
    // UISoundLookups.dbc
    DBCFileList[214].col_name[0] = "id";            DBCFileList[214].col_desc[0] = "Entry";
    // UnitBlood.dbc
    DBCFileList[215].col_name[0] = "id";            DBCFileList[215].col_desc[0] = "Entry";
    // UnitBloodLevels.dbc
    DBCFileList[216].col_name[0] = "id";            DBCFileList[216].col_desc[0] = "Entry";
    // Vehicle.dbc
    DBCFileList[217].col_name[0] = "id";            DBCFileList[217].col_desc[0] = "Entry";
    // VehicleSeat.dbc
    DBCFileList[218].col_name[0] = "id";            DBCFileList[218].col_desc[0] = "Entry";
    // VideoHardware.dbc
    DBCFileList[219].col_name[0] = "id";            DBCFileList[219].col_desc[0] = "Entry";
    // VocalUISounds.dbc
    DBCFileList[220].col_name[0] = "id";            DBCFileList[220].col_desc[0] = "Entry";
    // WeaponImpactSounds.dbc
    DBCFileList[221].col_name[0] = "id";            DBCFileList[221].col_desc[0] = "Entry";
    // WeaponSwingSounds2.dbc
    DBCFileList[222].col_name[0] = "id";            DBCFileList[222].col_desc[0] = "Entry";
    // Weather.dbc
    DBCFileList[223].col_name[0] = "id";            DBCFileList[223].col_desc[0] = "Entry";
    // WMOAreaTable.dbc
    DBCFileList[224].col_name[0] = "id";            DBCFileList[224].col_desc[0] = "Entry";
    //WorldChunkSounds.dbc
    DBCFileList[225].col_name[0] = "id";            DBCFileList[225].col_desc[0] = "Entry";
    // WorldMapArea.dbc
    DBCFileList[226].col_name[0] = "id";            DBCFileList[226].col_desc[0] = "Entry";
    // WorldMapContinent
    DBCFileList[227].col_name[0] = "id";            DBCFileList[227].col_desc[0] = "Entry";
    // WorldMapOverlay.dbc
    DBCFileList[228].col_name[0] = "id";            DBCFileList[228].col_desc[0] = "Entry";
    // WorldMapTransforms.dbc
    DBCFileList[229].col_name[0] = "id";            DBCFileList[229].col_desc[0] = "Entry";
    // WorldSafeLocs.dbc
    DBCFileList[230].col_name[0] = "id";            DBCFileList[230].col_desc[0] = "Entry";
    // WorldStateUI.dbc
    DBCFileList[231].col_name[0] = "id";            DBCFileList[231].col_desc[0] = "Entry";
    // WorldStateZoneSounds.dbc
    DBCFileList[232].col_name[0] = "";              DBCFileList[232].col_desc[0] = "";
    // WowError_String.dbc
    DBCFileList[233].col_name[0] = "id";            DBCFileList[233].col_desc[0] = "Entry";
    // ZoneIntroMusicTable.dbc
    DBCFileList[234].col_name[0] = "id";            DBCFileList[234].col_desc[0] = "Entry";
    // ZoneMusic.dbc
    DBCFileList[235].col_name[0] = "id";            DBCFileList[235].col_desc[0] = "Entry";
